rabbit:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
redis:
    image: redis
rabbitconsumer:
    image: adunicorn/rabbitconsumer
    links:
      - redis
      - rabbit