//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldIssuingService.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MiniIssuingEntities : DbContext
    {
        public MiniIssuingEntities()
            : base("name=MiniIssuingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CardHolder> CardHolder { get; set; }
        public virtual DbSet<Card> Card { get; set; }
        public virtual DbSet<Log> Log { get; set; }
    }
}
